spring:

  threads:
    virtual:
      enabled: true

  application:
    name: jflix

  datasource:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/jflix}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:t00r}