spring:

  threads:
    virtual:
      enabled: true

  application:
    name: jflix

  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:t00r}